version: "1.0"
info:
  model: int-scaffold
packages:
- name: KusiGit2207MCSPPPProject
  gitServerName: KusiMSCPPP
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
services:
- serviceName: project.kusigit2207mcsppp.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: KusiGit2207MCSPPPProject
    version: "1.0"
- serviceName: project.kusigit2207mcsppp.integrations:SIQAAdapterFlow
  packages:
  - name: KusiGit2207MCSPPPProject
    version: "1.0"
- serviceName: project.kusigit2207mcsppp.integrations:childFS
  packages:
  - name: KusiGit2207MCSPPPProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.2064
- serviceName: project.kusigit2207mcsppp.integrations:parentFS
  packages:
  - name: KusiGit2207MCSPPPProject
    version: "1.0"
